# vim:ft=kitty
#: This is a template that can be used to create new kitty themes.
#: Theme files should start with a metadata block consisting of
#: lines beginning with ##. All metadata fields are optional.

## name: The name of the theme (if not present, derived from filename)
## author: The name of the theme author
## license: The license information
## upstream: A URL pointing to the location of this file upstream for auto-updates
## blurb: A description of this theme. This must be the
## last item in the metadata and can continue over multiple lines.

#: All the settings below are colors, which you can choose to modify, or use the
#: defaults. You can also add non-color based settings if needed but note that
#: these will not work with using kitty @ set-colors with this theme. For a
#: reference on what these settings do see https://sw.kovidgoyal.net/kitty/conf/

#: The basic colors

foreground                      #fdf0ed
background                      #16161c
selection_foreground            #16161c
selection_background            #fdf0ed


#: Cursor colors

# cursor                          #cccccc
# cursor_text_color               #111111


#: URL underline color when hovering with mouse

# url_color                       #0087bd


#: kitty window border colors and terminal bell colors

# active_border_color             #00ff00
# inactive_border_color           #cccccc
# bell_border_color               #ff5a00
# visual_bell_color               none


#: OS Window titlebar colors

# wayland_titlebar_color          system
# macos_titlebar_color            system


#: Tab bar colors

# active_tab_foreground           #000
# active_tab_background           #eee
# inactive_tab_foreground         #444
# inactive_tab_background         #999
# tab_bar_background              none
# tab_bar_margin_color            none


#: Colors for marks (marked text in the terminal)

# mark1_foreground black
# mark1_background #98d3cb
# mark2_foreground black
# mark2_background #f2dcd3
# mark3_foreground black
# mark3_background #f274bc


#: The basic 16 colors

#: black
color0 #16161c
color8 #2e303e

#: red
color1 #f43e5c
color9 #f43e5c

#: green
color2  #27d796
color10 #27d796

#: yellow
color3  #fac29a
color11 #fac29a

#: blue
color4  #6c6f93
color12 #6c6f93

#: magenta
color5  #de87bc
color13 #de87bc

#: cyan
color6  #25b2bc
color14 #25b2bc

#: white
color7  #6e707e
color15 #ffffff


#: You can set the remaining 240 colors as color16 to color255.
