# Documentation: https://sw.kovidgoyal.net/kitty/conf/

font_family Iosevka Slab
font_size 10.0
disable_ligatures always
font_features none
modify_font cell_width 100%

box_drawing_scale 0.001, 0.5, 1, 2

undercurl_style thin-sparse

cursor none
cursor_beam_thickness 1.0
cursor_blink_interval 0
cursor_trail 0

mouse_hide_wait 0
focus_follows_mouse yes
default_pointer_shape arrow

enable_audio_bell no

confirm_os_window_close 0

# background_opacity 0.96

# BEGIN_KITTY_THEME
include themes/horizonish.conf
# END_KITTY_THEME
